### ISSUE TITLE
jStat.triangular.pdf(x, a, b, c) returns NaN instead of 1 when c = a and x = a

### ISSUE THREAD

**Issue by akrawitz** [jstat/jstat#101]
`jStat.triangular.pdf(x, a, b, c)` returns `NaN` instead of `1` when `c` = `a` and `x` = `a`. For example: jStat.triangular.pdf(2, 2, 4, 2) returns `NaN` instead of `1`,

**Comment by trevnorris** [comment]
Fixed by 8a992a1.

**Comment by akrawitz** [comment]
I must apologize for providing the wrong fix for this NaN. When `x = c`, the correct value in the general case is `2 / (b - a)`, not '1'. (Although '1' happened to be the correct value for the example provided.) For a clear definition of the PDF across all possible values see the [Wikipedia page for the Triangular distribution](https://en.wikipedia.org/wiki/Triangular_distribution).  I will make a pull request with a fix. (My first pull here, so apologies in advance for any technical or etiquette mistakes.)

**Comment by trevnorris** [comment]
No worries, and thanks for coming back once you caught the issue.
