### ISSUE TITLE
Some CDF functions return incorrect values outside of support

### ISSUE THREAD

**Issue by akrawitz** [jstat/jstat#104]
The cumulative distribution function (CDF) for a probability distribution should be well-defined for any value of `x` (assuming the values provided for the parameters of the distribution are "legal"). If the support for a distribution is left-bounded, then the CDF should be `0` below the left bound. If the support for a distribution is right-bounded, then the CDF should be `1` above the right bound.
The `cdf` functions for the distributions listed below return incorrect values above and/or below the support. Some of the functions return `NaN` or other non-numeric values, while others return nonsensical numeric values.
* `centralF` - below
* `chisquare` - below
* `gamma` - below
* `invgamma` - below
* `kumaraswamy` - below & above
* `lognormal` - below
* `pareto` - below
* `triangular` - above

**Comment by akrawitz** [comment]
Submitted pull request #157 that fixes this issue, and adds tests for these cases.

**Comment by trevnorris** [comment]
Fixed by 6840ac23a.
