### ISSUE TITLE
Gammap error?

### ISSUE THREAD

**Issue by rsrandhawa** [jstat/jstat#117]
Hi, I was unable to get gammap(a,x) to corroborate with Mathematica values. gammap(a,x) should equal Mathematica's Gamma[a,0,x] function. 
Fix(?): if one calculates gammap(a,x)*gammafn(a), then this does equal Mathematica's Gamma[a,0,x].

**Comment by fasiha** [comment]
Please consider adding a boolean third argument to gammap allowing the user to skip the scaling in `gammap` by `gammafn(x)`. The default can be such that it does scale it, as it currently stands.

This will be helpful, e.g., when evaluating the *upper* incomplete gamma function. Right now we have to do this: 
```js
function gammaUpper(x, a) { return jStat.gammafn(x) - jStat.gammap(x, a); }
```
which requires *two* calls to `gammafn` (one inside gammap and one outside, to undo it). If `gammap` could be instructed *not* to scale the definite integral with `gammafn(x)`, then this `gammaUpper` could be do `1 - gammap(x, a, false)`, and then scale with `gammafn` if desired (if you want the unregularlized version), avoiding at least one, possibly two calls to `gammafn`.

**Comment by jamescgibson** [comment]
Hi @fasiha,

There is the `jStat.lowRegGamma()` function that `gammap` calls, which returns the lower regularized gamma function. 

Right now `gammap` is just `lowRegGamma * gammafn`. Would this help?

If you have some thoughts on how to best implement the full set of gamma functions, I'd love to hear them; you mention a boolean flag but I worry that boolean flags have too much opportunity for mistakes to be made.

**Comment by fasiha** [comment]
Aha!!! Got it, thanks!
