### ISSUE TITLE
Lower incomplete gamma function arugment order switched?

### ISSUE THREAD

**Issue by fasiha** [jstat/jstat#129]
I think that, in both the source and the documentation, the order of the lower incomplete gamma functions is switched. Currently both say, `gammap( a, x )`, which leads me to believe that the upper bound of the integrand is `a` while the argument is `x` (matching `gammafn(x)`). However, the function treats "`a`" as the argument value, and "`x`" as the integral's upper bound: compare jStat with mpmath (bundled with SymPy, runnable at http://live.sympy.org/):

```js
var x = 5.5, bound = 3.3;
jStat.gammap(bound, x) // 2.369679820488629, wrong!
jStat.gammap(x, bound) // 8.872618009415675, correct
```
vs
```python
x = 5.5
bound = 3.3
mpmath.gammainc(x, a=0, b=bound) # 8.8726179845135089
```
(In mpmath, the first argument is the value (`x`), and `a` and `b` are the integral limits.)

I know it's a choice of notation, but the notation differs between `gammafn` and `gammap`, which is probably not what you want.

Anyone using this function will have discovered this and they'll be using it as if it was defined as `gammap(x, a)`, so I think it'd be most reasonable to just swap the order of arguments in the source and documentation to `x, a`, if you agree that this is a problem.

**Comment by jamescgibson** [comment]
Good catch. The gamma(a, x) notation parallels Mathematica's labeling, which is why it was chosen. I'll create a PR to switch the documentation for `jStat.gammafn(x)` to `jStat.gammafn(a)` so that the labeling is consistent. 

Since the tests check against values from Mathematica, it seems like this is the easiest way to label it.  

Thanks for the bug report!

**Comment by fasiha** [comment]
Glad to help, thanks for your appreciative words!

Personally I think of `a` (& `b`) as integration bounds while `x` (or `z`) a possibly-complex argument but now I see that that's how Mathematica does it :open_mouth: ! 

I beg you to add some documentation to `gammap` that explains this, perhaps ideally by just writing out the definitional integral?

**Comment by fasiha** [comment]
Actually, I see that Mathematica also uses `z` (our `x`) for Gamma but switches to `a` for incomplete Gamma (and uses `z`/`x` as a bound). So confusing to me...

**Comment by jamescgibson** [comment]
I'll see about adding mathjax to the docs so that we can put integrals in
the documentation. I'll definitely add more documentation making this
clear.

Thanks!
