### ISSUE TITLE
Add non-central t distribution

### ISSUE THREAD

**Issue by kbroman** [jstat/jstat#131]
It might be useful to add the non-central t distribution, which is helpful for power calculations.

I've written some code, at the bottom of [this file](https://github.com/kbroman/d3examples/blob/master/ttest_power/distributions.coffee) (functions `pnct` and `dnct` for the CDF and density, respectively). It's CoffeeScript and not pretty, but may be useful.

I think I could work it up into a proper pull request, but do you want all of the different parts for a distribution (mean, mode, etc.) or are the pdf and cdf sufficient?

**Comment by trevnorris** [comment]
@kbroman for the time being as much as you have will be sufficient.

**Comment by kbroman** [comment]
I tried [adding code for the PDF and CDF of the non-central-t](https://github.com/kbroman/jstat/commit/62a2120d7d614132d49b71f59b9f89ca6a0035f6), but the tests in comparison to R show the algorithm I'm using behaves very poorly for large values of the non-centrality parameter. Need to find a different method and can't use R's code because GPL.

**Comment by kbroman** [comment]
If I [force use of at least 200 iterations](https://github.com/kbroman/jstat/commit/1fd6a0c875c5bb1f2bd6e211de8e83a4a1231bd6), the tests for largish non-centrality parameter values now pass. So I need to study the convergence criterion further. (The approximation can work, as long as one goes far enough out in the tail.)

**Comment by jamescgibson** [comment]
For what it's worth most of the current algorithms work poorly for large parameters anyway.

**Comment by jamescgibson** [comment]
@kbroman Is there any objection to us pulling your code upstream? Would love to get this distribution into the library! :+1:

**Comment by kbroman** [comment]
I'd be very glad to have my code used; should I submit a proper pull request?

**Comment by jamescgibson** [comment]
If you can, please do! :+1: I'm happy to cherry-pick your code out if it would be time-prohibitive, but love to have the proper people added to GitHub's PR-tracking.

**Comment by trevnorris** [comment]
Fixed by 7e5d94f51. Working on a release, but npm is having some issues.

**Comment by trevnorris** [comment]
Fixed by 648342ad.
