### ISSUE TITLE
MIT-LICENSE.txt filename prevents WebJar deployment

### ISSUE THREAD

**Issue by mackler** [jstat/jstat#145]
Hi:

I want to deploy `jstat` as a WebJar using the tool at http://www.webjars.org/bower, but am unable to do so because of the name of the file `MIT-LICENSE.txt`.  The exact error message I got is:

>Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

Is there any chance I could persuade the developers of this project  to enable its deployment as a WebJar by adding a (non-array) `license` property to the `package.json` object?  I'm not an expert, but looking at other projects and [this page](https://docs.npmjs.com/files/package.json#license) suggests the following might work:

    "license": "MIT",

Or else just rename the license file `LICENSE.txt`?  Or, alternatively, to take some other action that would make this possible (including telling me that the problem is on my end and what I'm doing wrong)?

Thanks!!

**Comment by jamescgibson** [comment]
I'm not familiar with web jars at all, but I see no reason not to merge a PR that renames MIT-LICENSE.txt to LICENSE.txt.

**Comment by mackler** [comment]
> I'm not familiar with web jars at all, but I see no reason not to merge a PR that renames MIT-LICENSE.txt to LICENSE.txt.

Thank you for the invitation.  I have submitted [Pull Request 146](https://github.com/jstat/jstat/pull/146).
