### ISSUE TITLE
Dead links on _toc.md page

### ISSUE THREAD

**Issue by NorthDecoder** [jstat/jstat#161]
The Table of Contents page at
  https://github.com/jstat/jstat/blob/master/doc/md/_toc.md
has dead links.
For example
  https://github.com/jstat/jstat/blob/master/doc/md/overview.html
  results in a 404 page not found error
  
It could be set to
  https://github.com/jstat/jstat/blob/master/doc/md/overview.md
where the suffix 'html' is replaced by 'md'.

**Comment by jamescgibson** [comment]
Thanks for the bug report! I'll take care of this later today.

**Comment by trevnorris** [comment]
@jamescgibson Can this be closed?

**Comment by NorthDecoder** [comment]
I may not be looking at the correct branche(es) however it appears that no fix is in place yet, so I created a [pull](https://github.com/jstat/jstat/pull/164) request with the proposed [fix]
(https://github.com/jstat/jstat/commit/ef461a739b162162be3bc18e23211ab1cde0f590). I have found the library to be useful and wanted help out appropriately!.

**Comment by jamescgibson** [comment]
Closed by #164

**Comment by trevnorris** [comment]
Note: That PR was reverted because it broke the generated web documents.

**Comment by jamescgibson** [comment]
@trevnorris My mistake. Will address now then.
