### ISSUE TITLE
Add Laplace (Double Exponential) Distribution functions

### ISSUE THREAD

**Issue by dylancwood** [jstat/jstat#162]
I was recently tasked with using jStat to sample random variables from a Laplace CDF. This can be done using the exsitng `jStat.exponential` functions, but it would be convenient if there were built in Laplace functions.  Would you be interested in merging a Pull Request that contained Laplace `pdf`, `cdf` and `inv` functionality?

**Comment by trevnorris** [comment]
Sure thing. Most of this library exists because of community contributions. :)
