### ISSUE TITLE
gauss_jacobi, mutating inv, aug

### ISSUE THREAD

**Issue by acthp** [jstat/jstat#167]
There are no docs, tests, or examples for gauss_jacobi, so it's rather hard to guess how to use it. I tried various permutations of jStat objects, js objects, different orientations, without success, along the lines of this:

    jstat.gauss_jacobi([[1, 0], [0, 1]], [[5], [3]], [[1], [1]], 0.01); 

Digging in, I found that the variable 'd' is being mutated in the call to ```inv```, and ```inv``` in general is mutating, due to the call to ```aug```. It seems unlikely that this is desired: is ```inv``` really supposed to return the inverse and mutate the input?

The mutation occurs because ```aug``` makes a shallow copy and mutates the nested reference types with ```push```. It happens when passing js or jStat objects. I could get the above example to work by replacing ```aug``` with this:

    return a.map(function (row, i) { return row.concat(b[i]); });

however that doesn't work with jStat objects.

**Comment by trevnorris** [comment]
Added that over 4 years ago. At the time I think a lot of those came from translating from existing implementations as best I could. (not a statistician myself) and didn't have any tests setup to verify the values. Do you know of a good existing implementation I could look at?

**Comment by acthp** [comment]
This bug report doesn't really require much in the way of tests, because the root is not the ```gauss_jacobi``` method, it's the ```aug``` method, which is quite easy to test. It shouldn't corrupt its inputs. The bug is that it does. A simple unit test should suffice.

As far as testing gauss_jacobi, I would recommend testing against R. Coincidentally, I just wrote a generative test against R for kaplan-meier methods, using jsverify, in this repo:

https://github.com/acthp/kaplan-meier

Specifically this file:

https://github.com/acthp/kaplan-meier/blob/master/test/km-test.js

It's somewhat horrible in that it writes a file out for each test case, but it was the best I could do on short notice without knowing R better. Due to the slowness of running R this way, I have to start mocha like ```mocha --timeout 0```.

**Comment by trevnorris** [comment]
Thanks for the report. Issue should be fixed, and released in 1.4.5.
