### ISSUE TITLE
spearmancoeff edgecase error

### ISSUE THREAD

**Issue by pratapvardhan** [jstat/jstat#172]
Output for `[1, 2, 3, 4], [5, 5, 5, 5]` is `1`
```js
jStat.spearmancoeff([1, 2, 3, 4], [5, 5, 5, 5])
1
```
Expected should have been undefined. (NaN or soemthing alike but not 1)

Since the standard deviation is zero in `arr2` and there is only 1 rank here.

**Comment by jamescgibson** [comment]
I've created a failing test for this case and confirmed that NaN follows the convention for other statistical software like R.

I don't believe that the current spearmancoeff implementation handles ties at all. I will investigate this, though another option would be to simply throw NaN if there are any ties, and document accordingly.

**Comment by pratapvardhan** [comment]
@jamescgibson -- Thanks. I've implemented spearmancoeff for ties and submitted the PR.

**Comment by jamescgibson** [comment]
:+1: Beautiful, thank you

**Comment by jamescgibson** [comment]
Thanks. Closed in ccddd66c7e61126c0c44110e0fb1c5f1f2863aea
