### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by swashcap** [jstat/jstat#183]
Could please you `npm publish` so the latest is available to NPM users? Looks like 1.1.5 is the most recent:

![latest-jstat](https://cloud.githubusercontent.com/assets/1858316/12340011/2a680292-bacd-11e5-9d03-92c858ffdd3e.jpg)

This workflow could be automated, possibly alongside the work happening in #142. My colleauge Mr. Daringer set up some [nice NPM scripts in one of our projects](https://github.com/MRN-Code/penny-collector/blob/381fa12e5275910f8fd0dad1b4f4635b6682918e/package.json#L14-L16):

```js
"scripts:" {
  //...
  "publish-patch": "npm run preversion && npm version patch && git push origin master --tags && npm publish",
  "publish-minor": "npm run preversion && npm version minor && git push origin master --tags && npm publish",
  "publish-major": "npm run preversion && npm version major && git push origin master --tags && npm publish",
  //...
}
```

I can assist if you need some help!

**Comment by trevnorris** [comment]
Updated. The package is technically `jStat` and not `jstat`. The latter was published on accident, but I'll try and remember to update both on release.
