### ISSUE TITLE
Mention jStat usage on the client side in Readme?

### ISSUE THREAD

**Issue by daluu** [jstat/jstat#184]
I notice the Readme only mentions NodeJS for usage, however, from what I read in this [book](http://onlinelibrary.wiley.com/doi/10.1002/9781119209386.ch8/summary) and testing it out myself, jStat works on client side as well.

Sadly that book and this project's Readme both do not explicitly state usage instructions for client side. The module loader tidbit of the Readme might be helpful info to the reader for those using module loaders, and RequireJS and NodeJS tidbit might be relevant for those that reference JS libraries the node way on client side (having to use special wrapper tools to do a require on client side).

But from a pure client side barebones usage, testing on Chrome browser, it looks like you can just reference the library script (locally or via CDN) in a script tag and then access jStat. And it looks like jStat (or j$) is usable as a member within the `this` object, although it is aliased to be called without `this` as well.

I ended up using it like such:

```
<script src="components/jstat.js"></script>
<script>
...
var jstat = this.jStat(dataset);
...
data[i]['cum'] = jstat.normal(jstat.mean(), jstat.stdev()).cdf(data[i].x);
...
</script>
```

I'm just mentioning here as clarification will help novices use jStat, as it currently is vague whether this is usable on client vs server side, and the exact steps to use client side.

**Comment by trevnorris** [comment]
That's correct. The most minimal usage is in `test/index.html`. I visit that file in the browser when I want to test something in the browsers console.

Will make a note of this in the README. Thanks for bringing it to my attention.
