### ISSUE TITLE
NODE_PATH in Makefile

### ISSUE THREAD

**Issue by gungorbudak** [jstat/jstat#188]
I think instead of using `NODE_PATH ?= ./node_module` in `Makefile`, we should use `NODE_PATH = ./node_module` or better we can try to get absolute path to the current directory and add it to the path.

Because I didn't have `uglifyjs` installed globally and I got this error:

``` bash
gungor@gungors-mint ~/projects/jstat $ make
Cleaning up build files
Building jStat
Minifying jStat
/bin/sh: 1: /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript/uglify-js/bin/uglifyjs: not found
make: *** [jstat.min.js] Error 127
```

Well, there is nothing wrong with installing it globally but I really like when dependencies don't require `sudo` which is one of the reasons I like Node.js.

**Comment by trevnorris** [comment]
Mind taking a look at https://github.com/jstat/jstat/pull/142? Let's make sure this addresses your concern.

**Comment by kgryte** [comment]
@trevnorris This can be closed.
