### ISSUE TITLE
Browser/node compatibility

### ISSUE THREAD

**Issue by nicolashefti** [jstat/jstat#197]
Hi,

I am currently working with [formulajs](https://github.com/sutoiku/formula.js) a project using jStats as dependency. The library use the following notation to import the module:

`var jStat = require('jStat').jStat;`

After building it with Webpack, the library works well in node but not in a browser. I think it is related to this [comment](https://github.com/jstat/jstat/issues/54#issuecomment-6551930).

Any idea how to make the formulajs library works for node and in a browser?

**Comment by nicolashefti** [comment]
Maybe with a bit of code:

This works (in node context):
```
formulajs = require('./dist/formula');

console.log(formulajs.AVEDEV(2,4,8,16));
```

This doesn't (because jStat is directly attached to the window Object): 
```
<!-- Numeric -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js"></script>
<!-- Numeral.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>
<!-- jStat -->
<script src="https://cdn.jsdelivr.net/jstat/latest/jstat.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/formulajs/1.0.8/formula.js"></script>
<script>
    console.log(formulajs.AVEDEV(2,4,8,16));
</script>
```

unless you insert this no-so-clean little trick (to fake the module import like in node):
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/numeral.js/1.4.5/numeral.min.js"></script>
<script src="https://cdn.jsdelivr.net/jstat/latest/jstat.min.js"></script>
<script>
    jStat.jStat = jStat;
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/formulajs/1.0.8/formula.js"></script>
<script>
    console.log(formulajs.AVEDEV(2,4,8,16));
</script>
```

**Comment by trevnorris** [comment]
stwo changes I could make. the one you suggest is good, to have `jStat.jStat = jStat`. makes life simpler for referencing reasons. the other is to add the conditional and do the proper `module.exports = jStat;` so only have to `require('jstat')` but the existing `require('jstat').jstat` will still work today. Should also solve the issue you're having in the browser. Sound good?
