### ISSUE TITLE
Random seed/repeatable draws

### ISSUE THREAD

**Issue by ddurschlag** [jstat/jstat#199]
It would be useful to be able to re-run a simulation with a fixed seed. The standard practice for this seems to be to use a non-built-in PRNG with a default seed, allowing the user to override the seed. There seem to be 8 references to Math.Random in the codebase, which doesn't seem super-hard to replace.

**Comment by trevnorris** [comment]
How do you think this should be accessible? It could be possible to set a global `jStat.setSeed(n)` where `n` is the seed you want. If `n === -1` then it uses the normal `Math.random()`. That sound like it might work?

**Comment by ddurschlag** [comment]
Not a huge magic-constant guy myself. Maybe just DI? "jStat.SetRandom(Math.random)" versus "jStat.SetRandom(GetPRNG(seed))" or similar would be my first choice, but beggars can't be choosers.

**Comment by trevnorris** [comment]
@ddurschlag I like that much better.

**Comment by trevnorris** [comment]
This isn't the most elegant solution, but would get the job done: https://github.com/jstat/jstat/commit/e1933c6256fbd043fd9be3425be5e651fa1fa9da

That look good to you?

**Comment by ddurschlag** [comment]
Looks fine to me -- it would be appreciated, however, if you included an alternative PRNG with the package. I know users can provide their own (which is great), but having one that you've done some basic testing on (e.g., for performance and distribution) would save users a PRNG odyssey -- which is often a real rat-hole.

**Comment by trevnorris** [comment]
@ddurschlag Best I could do here is use someone else's PRNG. I'm not sure what constitutes a "correct" PRNG implementation.

(https://github.com/davidbau/seedrandom for ref)

**Comment by hojBC** [comment]
Is there a reason this e1933c6 has not yet been merged?  It would be very useful for me.

**Comment by trevnorris** [comment]
@hojBC Landed that in f7bd2cf550a2a512ed511fb9cc08c246eb71825c

**Comment by trevnorris** [comment]
Made the change to allow setting a custom random function in c8eeaacd20bd8639dd2cf91a203467840c2e0461.
