### ISSUE TITLE
question regarding Spearman correlation coefficient implementation

### ISSUE THREAD

**Issue by pieterlukasse** [jstat/jstat#200]
I have been experimenting a bit with your code as I need the spearman function to be much faster. The reason is that I need to use it for a distance metric in a javascript clustering algorithm (see https://github.com/cBioPortal/cbioportal/pull/1998). 

Looking at the code (and at the theory), I think the [`jStat.spearmancoeff` function](https://github.com/jstat/jstat/blob/master/src/vector.js#L381) could also be written as

```javascript
jStat.spearmancoeff =  function (arr1, arr2) {
  arr1 = jStat.rank(arr1);
  arr2 = jStat.rank(arr2);
  //return pearson's correlation of the ranks:
  return jStat.corrcoeff(arr1, arr2);
}
```

My tests show this is quite faster than the current implementation and seems to give same (or very very similar) results (at least in the clustering outcome). My question is: do you also think the code I'm proposing here is preferable? If not, can you maybe give some extra information about why the **_current_** implementation is preferred? 

Thanks!

**Comment by yiyuezhuo** [comment]
I think your proposing is preferable. The current implementation's functional programming style may reduce performance. And your proposing is brief and correct.

**Comment by pieterlukasse** [comment]
Nice! I will make a PR.

**Comment by trevnorris** [comment]
Fixed in https://github.com/jstat/jstat/pull/201
