### ISSUE TITLE
Runtime error in strict mode enabled javascript engine

### ISSUE THREAD

**Issue by sriragavan** [jstat/jstat#203]
In [linearalgebra.js (line #286)](https://github.com/jstat/jstat/blob/master/src/linearalgebra.js#L286), the local variable c is not declared hence fails during runtime in strict mode enabled javascript engines like mozilla spidermonkey.

`
      c = m[y][y];
      for (var y2 = 0; y2 < y; y2++) {
        for (var x = w-1; x > y-1; x--) {
          m[y2][x] -= m[y][x] * m[y2][y] / c;
        }
      }
`

The above code works fine in node environment with out any changes.

**Comment by trevnorris** [comment]
Fixed by 81b7bca8b1b8966965199f15469391cfa9a2daf1 and released in [1.6.1](https://github.com/jstat/jstat/releases/tag/1.6.1)
