### ISSUE TITLE
t-test: p-value with a t-score from samples of unequal size? 

### ISSUE THREAD

**Issue by kyssproject** [jstat/jstat#204]
If I have `value1` and `value2` with `n1!=n2`, I can calculate the `t_score` as said here
https://en.wikipedia.org/wiki/Student's_t-test#Equal_or_unequal_sample_sizes.2C_equal_variance

Then, to get the p-value with jStat I (think I) can use

`jStat.ttest( tscore, n, sides)`

But I do have two `n` here. How can I do this? Or am I missing something?

**Comment by yiyuezhuo** [comment]
From your reference:

>  In these formulae, ni − 1 is the number of degrees of freedom for each group, and the total sample size minus two (that is, *n1 + n2 − 2*) is the total number of degrees of freedom, which is used in significance testing.

The *n1 + n2 - 2* is the **degrees of freedom** that you need set as parameter for t-distribution. You can read https://en.wikipedia.org/wiki/Degrees_of_freedom_(statistics) to get the core concept.

**Comment by kyssproject** [comment]
Yes, after posting I was supposing this but with your confirmation now I'm confident. Thanks!
