### ISSUE TITLE
Median absolute deviation calculation appears to be incorrect

### ISSUE THREAD

**Issue by tmcw** [jstat/jstat#205]
Hello maintainers! Great work on this library. I've been benchmarking it against a bunch of others, and it holds up very well. One thing that I dug into was jStat's high performance for medianAbsoluteDeviation, which seemed unusual. In this case, the method is named [meddev](https://github.com/jstat/jstat/blob/master/src/vector.js#L246-L254).

jStat's technique is:

1. Take the median of the input
2. Take the mean of total absolute deviations from that median value

This, as far as I can tell, isn't the same as what a median absolute deviation value should be, and jStat's calculation notably doesn't match [the canonical wikipedia example](https://en.wikipedia.org/wiki/Median_absolute_deviation). Its high performance was caused by taking the mean, rather than the median, of total deviations. The correct technique would be:

1. Take the median of the input
2. Take the median of absolute deviations from that median value

Thoughts? I've cross-checked this against Wikipedia, my implementation (simple-statistics), and mathjs, and they all give the same result for an input of `1, 1, 2, 2, 4, 6, 9`, the number 1, whereas jStat returns 2.142857142857143.

**Comment by trevnorris** [comment]
So you're saying `var mean = jStat.mean(arr);` should actually be `var mean = jStat.median(arr);`?

**Comment by trevnorris** [comment]
@tmcw I believe https://github.com/jstat/jstat/pull/208 fixes the issue. Mind checking? I'll land this and do a new release with the fix once it's verified.
