### ISSUE TITLE
jStat.chisquare.inv wrong behaviour : Am I missing something ?

### ISSUE THREAD

**Issue by dedesite** [jstat/jstat#218]
Hi,

First of all I'm not good at statistics at all, so maybe my problem is irrelevant but I don't understand one thing with your chisquare implementation.

When I try for exemple jStat.chisquare.inv with p = 0.5 and dof = 1 like this
`jStat.chisquare.inv(0.5, 1)`
It gave me 
`0.45493642311961857`

Which is exactly what LibreOffice gave me when I use
`=CHIINV(0,5;1)`

And it is also similar to what we can find in any chi square table available online.

But when I try with p=0.05 i got 
`0.003932140000019863`

Which is very different from what LibreOffice gave me which is `3.841458821`, which is also similar to what we can find in chi square table.

So my question is : why is there such a difference in chisquare.inv results ? And is there a way to find `3.841458821` with `p=0.05` with jStat ?

Thanks,
Andréas

**Comment by yiyuezhuo** [comment]
It seems LibreOffice  give you "right tail result", instead of that, standard statistic software tend to give left tail probability consistently. You should use `jStat.chisquare.inv(0.5, 1) to get LibreOffice result. But the left tail usage is recommended.

**Comment by dedesite** [comment]
Ohh, ok that's why it worked with p=0.5. Thank you for your explanation, as I say, I'm really not good with statistics...
