### ISSUE TITLE
adjusted_R2 in OLS model not calculated

### ISSUE THREAD

**Issue by EloquentData** [jstat/jstat#219]
https://github.com/jstat/jstat/blob/46891b79cebc28160e286d994ec5c5242a56e13f/dist/jstat.js#L4693

Calculation based on model.rsquared, which does not exist. Should be model.R2

**Comment by trevnorris** [comment]
do you have a fix for what this line should be?

**Comment by EloquentData** [comment]
1 - (1 - model.R2) * ((model.nobs - 1) / (model.df_resid));

**Comment by jamescgibson** [comment]
Unless someone has already grabbed this, I have put time on my calendar to fix it tonight.

**Comment by jamescgibson** [comment]
OK, I've opened a PR for this issue and further added some documentation and tests for the OLS module.

**Comment by EloquentData** [comment]
Thank you for the fix!
