### ISSUE TITLE
jStat percentile function is using inclusive, not exclusive (as mentioned in the documentation)

### ISSUE THREAD

**Issue by viswanathr88** [jstat/jstat#224]
I just took 200 values and compared what i get using excel's
PERCENTILE.INC and PERCENTILE.EXC with jStat results.

The documentation of jStat says percentile is exclusive, but the results are the same as the PERCENTILE.INC function. Am i missing something here?

**Comment by viswanathr88** [comment]
I think the problem is here:
if (index + 1 < _arr.length) {
    return _arr[index] * (1 - frac) + _arr[index + 1] * frac;
}
Shouldn't it be the reverse for exclusive?
return _arr[index] * frac + _arr[index + ] * (1- frac);

The value that is closer to the next element is being picked in the case of jStat instead of picking the one closer to index?

**Comment by arturaugusto** [comment]
I also checked this. The tests are comparing with inclusive results.

**Comment by viswanathr88** [comment]
Can we please get a function for EXC? Lot of other apps I use seem to do EXC.

**Comment by arturaugusto** [comment]
Try using this build:
https://github.com/arturaugusto/jstat/blob/master/dist/jstat.min.js
setting true to the exclusive flag, this way:
`jStat.percentile([1, 2, 3, 4], 0.3, true)`
And check if you get correct results.
