### ISSUE TITLE
Vows Github Package reference

### ISSUE THREAD

**Issue by KamalAman** [jstat/jstat#233]
JStat currently references Vows github page as its dependency.

```
    "vows" : "https://github.com/flatiron/vows/archive/master.tar.gz"
```

Referencing Vows this way will always pull down the latest code on vows, regardless of their version and breaking changes. However the real issue comes for people using `Yarn` with a `Yarn.lock` file that expects the hash of a dependency at a specific "version" to not change randomly.

Vows has been published to npm, https://www.npmjs.com/package/vows. Vows should referenced by its version number.

**Comment by kgryte** [comment]
@trevnorris This can be closed.
