### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [jstat/jstat#240]
Hi, what is the current status of this project? Is it still maintained?

**Comment by chrislawes79** [comment]
From what I can gather it is a bit of a mish-mash of different content creators so no one person can clearly resolve any issues. Seems to be dead?

**Comment by jamescgibson** [comment]
I know I"ve missed some things, but I'll try to keep up with any actual errors.

**Comment by trevnorris** [comment]
After over a year of leaving open source, for various reasons, I'm back. Worked through all the PR's today and did the release of [1.8.1](https://github.com/jstat/jstat/releases/tag/1.8.1).

Soon I plan on starting work on v2.x that'll switch to using Typed Arrays, along with the other goodies that are supported by browsers today.
