### ISSUE TITLE
Looking for equivalent to statsmodels.tsa.stattools.adfuller

### ISSUE THREAD

**Issue by runvnc** [jstat/jstat#252]
Hello, I am looking for an Augmented Dickey-Fuller test like statsmodels.tsa.stattools.adfuller in Python.  Or something close.  Does jstat have that or anything like it (or maybe another JavaScript library)?  Or if not, maybe its not super hard to build it using functions that jstat has?
Thanks very much for any advice.

**Comment by trevnorris** [comment]
Sorry. I just maintain the code and am not a statistics expert. Will require input from the community on this one.

**Comment by runvnc** [comment]
I just switched that part to use Python
