### ISSUE TITLE
jStat.studentt.inv returns very different result from Microsoft Excel equivalent INVT

### ISSUE THREAD

**Issue by taviroquai** [jstat/jstat#253]
Hi,

Excel function INVT(0.2, 5) returns ~ 1.4759

While jStat.studentt.inv(0.2, 5) returns ~ -0.9195

Any ideas? Thank you!

**Comment by arturaugusto** [comment]
Which version of Excel are you using?
I just tested with Excel 2010, and INV.T(0.2, 5) returns -0,9195.
I also checked jstat, and confirmed that it returns -0,9195.

**Comment by arturaugusto** [comment]
Looks like INV.T(0,1;5) returns -1,4759. Maybe a typo?

**Comment by taviroquai** [comment]
Excel 2013.

And I just opened the same file but in Libreoffice Calc 6.0 and it recognised as TINV (inverse t distribution), with same result ~ 1.475

=TINV(0.2, 5)

Maybe I'm using wrong function in jStat?

Thanks

**Comment by arturaugusto** [comment]
In Excel, try using `INV.T`, not `INVT`.

Looks like `INV.T` returns distribution left side, and `INVT` is a excel 2007 compatibility function that returns for both sides.

**Comment by arturaugusto** [comment]
Looks like:

`Math.abs(jStat.studentt.inv(x/2, 5))` ~ `INVT(x, 5)`

For any given x, if you need a `jStat` function compatible with excel `INVT`

**Comment by taviroquai** [comment]
That's right!

I'm converting and excel calculation to a JS app and x/2 seems to get the correct result.

Thanks! :)
