### ISSUE TITLE
jStat.oneSidedDifferenceOfProportions

### ISSUE THREAD

**Issue by jamessoley** [jstat/jstat#259]
I'm sure this is a stupid question but I'm stumped. I tried to import the jstat library into GBQ and run a simple different of proportions test (prop test in R). Below is my code:

## Function Creation
CREATE TEMPORARY FUNCTION prop_test(a FLOAT64, b FLOAT64, c FLOAT64, d FLOAT64)
 RETURNS FLOAT64
 LANGUAGE js AS
"""
  return jStat.twoSidedDifferenceOfProportions(a, b, c, d); // jStat.twoSidedDifferenceOfProportions(p1,n1,p2,n2)
"""
OPTIONS (
 library="gs://jhs_packages/dist/jstat.min.js"
);

## Query
Select  prop_test(.5,10000,.7,50000) as p_value

ERROR: jStat.twoSidedDifferenceOfProportions is not a function at prop_test(FLOAT64, FLOAT64, FLOAT64, FLOAT64) line 2, columns 15-16

Is the function called something that I'm not seeing?

**Comment by jamessoley** [comment]
Okay. I just dug through the source code and saw that the function name is actually:

jStat.fn.twoSidedDifferenceOfProportions(a, b, c, d);

Can you please update the documentation from here? https://jstat.github.io/all.html#jStat.oneSidedDifferenceOfProportions

**Comment by trevnorris** [comment]
Thanks for noticing this. Fix has been pushed and the online documentation has been updated.
