### ISSUE TITLE
Determinant of symmetrical matrix gives wrong answer

### ISSUE THREAD

**Issue by michaeleiseman** [jstat/jstat#270]
I have the following symmetrical matrix:

`const matrix = [[310, -228, -190, 108], [-228, 310, 108, -190], [-190, 108, 310, -228], [108, -190, -228, 310]]`

The determinant of this matrix is 0, but

`jStat.det(matrix) = 1974297600`

Why does jStat give me the wrong answer?

**Comment by michaeleiseman** [comment]
@trevnorris @debrice Thank you so much for fixing this!!!

**Comment by trevnorris** [comment]
Somehow forgot to publish this fix. Has now been published in v1.9.5.
