### ISSUE TITLE
geomean not useful for real world data, since `product(arr)` quickly over/underflows

### ISSUE THREAD

**Issue by jberryman** [jstat/jstat#280]
Taking the roots first and then product is the way I know to compute this, but I have no idea how to judge how much error to expect in that method. I was hoping for something more sophisticated in this library. Some different approaches are discussed here, but I have no idea how to judge them or determine if my implementation was correct if I were to try to implement one:

https://stackoverflow.com/questions/37715250/safe-computation-of-geometric-mean
https://stackoverflow.com/questions/19980319/efficient-way-to-compute-geometric-mean-of-many-numbers

**Comment by kgryte** [comment]
Better is to compute the natural log, sum, and then exponentiate. https://github.com/stdlib-js/stdlib/tree/116787012ece738172c5e80cc0bb20296d471793/lib/node_modules/%40stdlib/stats/incr/gmean and https://github.com/stdlib-js/stats-incr-gmean.

**Comment by jberryman** [comment]
Fwiw I also realized I could get some intuition for accuracy of different approaches by testing on e.g. `take n (cycle [2^3, 3^3, 4^3])` for different size `n`
