### ISSUE TITLE
jStat.studentt.inv giving wrong result

### ISSUE THREAD

**Issue by Lain27** [jstat/jstat#283]
Hi.
When the TINV function is called in excel with the following data it returns:
=T.INV((1-0.0455/2),3682117.54526179)
=2.00000312292887
(I'm using T.INV for single tail)
when using jsat it returns the wrong result
=jStat.studentt.inv((1-0.0455/2),3682117.54526179)
=2.0000030413298036

**Comment by kgryte** [comment]
The result is not necessarily wrong, just different. Computing `tinv` depends on many other numerical functions, which each use various approximations. That Excel and jstat might have different implementations, and thus different results, should be expected. If you are expecting exactly equal results, you're likely to be disappointed. Instead, so long as results are within a relative tolerance, you should be fine for most use cases.

**Comment by trevnorris** [comment]
Thanks for reporting. Will consider this resolved.
