### ISSUE TITLE
Not usable as a node.js module?

### ISSUE THREAD

**Issue by benbuckman** [jstat/jstat#54]
This library builds with npm and is listed in the npm directory, but it can't itself be `require()`'d like a module, and none of its files `export` any methods. Is that by design?

**Comment by mryellow** [comment]
Just a note for those to follow:

Using `this.j$ = this.jStat = (function( Math, undefined ) {` as noted above, means that it isn't immediately available upon loading with RequireJS.

RequireJS Shim config, need to use `init` to pass out that variable.

```
jstat: {
            exports: ['jStat'],
            init: function () {
                return {
                    jStat: jStat
                };
            }
        }
```

http://stackoverflow.com/a/28096524/2438830

**Comment by jamescgibson** [comment]
@mryellow: I'm not a node expert, but if this works in general could you make a PR to add this info to the Readme? I'm sure it'd be helpful for a lot of peopel!

**Comment by mryellow** [comment]
No problem, will push something later today.

Include `j$`? It choked on the `$`, figure needs to be in quotes.
