### ISSUE TITLE
Known Issue: Regression

### ISSUE THREAD

**Issue by ChrisRackauckas** [jstat/jstat#55]
There is a known issue with regression. It occurs due to some type checking (some things require a jStat object while others don't etc). It will get fixed in future.

**Comment by gibito** [comment]
Hi @ChrisRackauckas 
Is this issue the causes of the following error? 

**jStat(XTX_INV).multiply(XTY)**

// returns
[
 [NaN, NaN],
 [NaN, NaN]
]

where:

XTX_INV = [ 
              [6.1542056074766331,-0.2897196261682242],
              [ -0.289719626168224161, 0.014018691588785041]
];

XTY = [
             [322],
             [6746]
];

**Results, using Excel**
=MMULT(XTX_INV,XTY)

we get

[
  [27.20560748],
  [1.280373832]
]

**Comment by ChrisRackauckas** [comment]
I think the bigger fix for this will be once someone finishes the QR algorithm to re-implement the regression via QR. A quick explanation is here if anyone has the time to code it:

https://www.stat.wisc.edu/~larget/math496/qr.html

**Comment by trevnorris** [comment]
Awesome. Thanks for the additional information.
