### ISSUE TITLE
jStat.centralF.pdf(x, df1, df2) returns NaN when x = 0

### ISSUE THREAD

**Issue by akrawitz** [jstat/jstat#97]
`jStat.centralF.pdf(x, df1, df2)` returns `NaN` when `x` = `0`
The correct value depends on `df1` and `df2`, but it should always be well defined.

**Comment by jamescgibson** [comment]
This was closed by 0566f0736a826ab2552e5b68134d7336af85dabe. Closed.

**Comment by akrawitz** [comment]
While this now works when `df1 > 2`, it is still returning `NaN` when `df1 <= 2`. With `x = 0`, when `df1 = 2` then it should return `1`, and when `df1 < 2` (and greater than 0), then it should return `Infinity`.
