### ISSUE TITLE
jStat.kumaraswamy.pdf(x, alpha, beta) is incorrect for certain values

### ISSUE THREAD

**Issue by akrawitz** [jstat/jstat#99]
`jStat.kumaraswamy.pdf(x, alpha, beta)` is incorrect for certain parameter values. When `alpha` = `1` and `x` = `0` it returns `NaN` instead of returning a value equal to `beta`. Likewise, when `beta` = `1` and `x` = `1` it returns `NaN` instead of a value equal to `alpha`.

**Comment by akrawitz** [comment]
Just submitted a pull request.
Add special cases for the two instances where the 'log' form of the PDF
fails (when x = 0 and alpha = 1, and when x = 1, and beta = 1).
Also added extensive tests for the kumaraswamy.pdf() based on dkumar()
in R package VGAM. Note that there are a few cases where the R function
incorrectly returns NaN. You can confirm the correct values in these
cases by doing the math using the function for the PDF here:
https://en.wikipedia.org/wiki/Kumaraswamy_distribution

**Comment by trevnorris** [comment]
Fixed by a4cae10.
